config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :account
  resource :account, controller: 'account'

  resources :services, as: 'services'

  root 'home#index'
end

app/models/account.rb
require 'digest/sha1'

class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :authentication_keys => [:domain]

  validates_presence_of :name, :domain, :status, :email
  validates_uniqueness_of :domain
  validates_format_of :domain, with: /\A[a-z][a-z0-9-]*\z$/, multiline: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_inclusion_of :status, in: ['created', 'active', 'inactive']
  validates_confirmation_of :password
  validates_length_of :password, within: 8..72, on: :create

  after_create do |account|
    request 'add', account.domain
  end

  after_destroy do |account|
    request 'remove', account.domain
  end

  def password=(password)
    self.password_salt = SecureRandom.hex unless password_salt.present?
    super
  end

  def valid_password?(password)
    password_digest(password) == self.encrypted_password
  end

  def full_domain
    BaseDomain.format(domain)
  end

  protected

  # Redmine-compatible password encryption
  # SHA1(salt + SHA1(clear_password))
  def password_digest(password)
    if password_salt.present?
      Digest::SHA1.hexdigest(password_salt + Digest::SHA1.hexdigest(password))
    end
  end

  private

  def request(*args)
    return if Rails.env.test?
    request = File.join(Rails.root, 'bin', 'r1c-request')
    system(request, *args)
  end
end

app/models/account/parameter_sanitizer.rb
class Account::ParameterSanitizer < Devise::ParameterSanitizer
  def sign_in
    default_params.permit(:domain, :email, :password)
  end
  def sign_up
    default_params.permit(:domain, :name, :email, :password, :password_confirmation)
  end
end

app/models/account_status.rb
class AccountStatus

  def initialize(domain)
    @account = Account.find_by_domain(domain)
  end

  def change_to(status)
    @account.update_attributes!(status: status)
  end

end

app/models/base_domain.rb
class BaseDomain

  def self.name
    ENV.fetch('R1C_BASE_DOMAIN', 'localdomain')
  end

  def self.format(identifier)
    [identifier, name].join('.')
  end

end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :authenticate_account!
  def show
    respond_with(current_account)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  respond_to :json, only: [:index, :show]

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def devise_parameter_sanitizer
    if resource_class == Account
      Account::ParameterSanitizer.new(Account, :account, params)
    else
      super # Use the default one
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if account_signed_in?
      redirect_to account_path
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
  def account_service_url(account)
    # FIXME Redmine-specific location
    account_service_protocol + '%s/autologin' % BaseDomain.format(account.domain)
  end

  def account_status(account)
    {
      'created'   => _('Activating ...'),
      'active'    => _('Active'),
      'inactive'  => _('Inactive'),
    }.map do |k,v|
      content_tag('span', v, class: 'status-%s' % k)
    end.join.html_safe
  end

  def account_service_protocol
    Rails.env.production? && 'https://' || 'http://'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def _(s)
    s
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.slim
div.jumbotron
  h1= _('Project management bla bla bla')
  p= _('Here goes some sales mumbo jumbo ...')
  p
    a.btn.btn-lg.btn-success role='button' href=new_account_registration_path
      span.glyphicon.glyphicon-chevron-right
      = ' ' + _('Start a 30-day free trial')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>R1c</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='controller-<%= params[:controller].downcase.gsub(/[^a-z0-9]/, '-') %>'>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= _('Laboro') %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if account_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_account.email %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to ('My account'), account_path %></li>
                  <li><%= link_to ('My services'), services_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to ('Logout'), destroy_account_session_path, method: "delete" %></li>
                </ul>
              </li>

            <% else %>
              <li><%= link_to _('Login'), new_account_session_path %></a></li>
              <li><%= link_to _('Sign up'), new_account_registration_path %></a></li>
            <% end %>
            <li><a href="#"><%= _('Help') %></a></li>
          </ul>
          <!--
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
            </form>
          -->
        </div>
      </div>
    </nav>

    <div class='container-fluid'>
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>